// <auto-generated />
using System;
using BackendMafia.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendMafia.Data.Migrations
{
    [DbContext(typeof(MafiaAPIDb))]
    [Migration("20230702115904_MafiaFamily")]
    partial class MafiaFamily
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendMafia.Models.FinancialReports", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompaniesId")
                        .HasColumnType("integer");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Expense")
                        .HasColumnType("integer");

                    b.Property<int>("FamilyDonate")
                        .HasColumnType("integer");

                    b.Property<int?>("MafiaCompanyId")
                        .HasColumnType("integer");

                    b.Property<int>("NetIncome")
                        .HasColumnType("integer");

                    b.Property<int>("Revenue")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MafiaCompanyId");

                    b.ToTable("FinancialReports");
                });

            modelBuilder.Entity("BackendMafia.Models.MafiaCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MafiaFamiliesId")
                        .HasColumnType("integer");

                    b.Property<int?>("MafiaFamilyId")
                        .HasColumnType("integer");

                    b.Property<int?>("MafiaMemberId")
                        .HasColumnType("integer");

                    b.Property<int>("MafiaMembersId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MafiaFamilyId");

                    b.HasIndex("MafiaMemberId");

                    b.ToTable("MafiaCompanies");
                });

            modelBuilder.Entity("BackendMafia.Models.MafiaFamily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MafiaFamilies");
                });

            modelBuilder.Entity("BackendMafia.Models.MafiaMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Birthday")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MafiaFamiliesId")
                        .HasColumnType("integer");

                    b.Property<int?>("MafiaFamilyId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Phone")
                        .HasColumnType("integer");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MafiaFamilyId");

                    b.ToTable("MafiaMembers");
                });

            modelBuilder.Entity("BackendMafia.Models.FinancialReports", b =>
                {
                    b.HasOne("BackendMafia.Models.MafiaCompany", null)
                        .WithMany("FinancialReports")
                        .HasForeignKey("MafiaCompanyId");
                });

            modelBuilder.Entity("BackendMafia.Models.MafiaCompany", b =>
                {
                    b.HasOne("BackendMafia.Models.MafiaFamily", null)
                        .WithMany("MafiaCompanies")
                        .HasForeignKey("MafiaFamilyId");

                    b.HasOne("BackendMafia.Models.MafiaMember", null)
                        .WithMany("MafiaCompanies")
                        .HasForeignKey("MafiaMemberId");
                });

            modelBuilder.Entity("BackendMafia.Models.MafiaMember", b =>
                {
                    b.HasOne("BackendMafia.Models.MafiaFamily", null)
                        .WithMany("MafiaMembers")
                        .HasForeignKey("MafiaFamilyId");
                });

            modelBuilder.Entity("BackendMafia.Models.MafiaCompany", b =>
                {
                    b.Navigation("FinancialReports");
                });

            modelBuilder.Entity("BackendMafia.Models.MafiaFamily", b =>
                {
                    b.Navigation("MafiaCompanies");

                    b.Navigation("MafiaMembers");
                });

            modelBuilder.Entity("BackendMafia.Models.MafiaMember", b =>
                {
                    b.Navigation("MafiaCompanies");
                });
#pragma warning restore 612, 618
        }
    }
}
