// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(MafiaApiDbContext))]
    [Migration("20230709165800_AddHealthStrength")]
    partial class AddHealthStrength
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.MainAggregate.FinancialReports", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("Expense")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FamilyDonate")
                        .HasColumnType("numeric");

                    b.Property<int>("MafiaCompanyId")
                        .HasColumnType("integer");

                    b.Property<decimal>("NetIncome")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("MafiaCompanyId");

                    b.ToTable("FinancialReports");
                });

            modelBuilder.Entity("Domain.Entities.MainAggregate.MafiaCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("MafiaFamilyId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("MafiaFamilyId");

                    b.ToTable("MafiaCompanies");
                });

            modelBuilder.Entity("Domain.Entities.MainAggregate.MafiaFamily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("FamilyMoney")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("MafiaFamilies");
                });

            modelBuilder.Entity("Domain.Entities.MainAggregate.MafiaMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Birthday")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("Health")
                        .HasColumnType("integer");

                    b.Property<int>("MafiaFamilyId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Strength")
                        .HasColumnType("integer");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("MafiaFamilyId");

                    b.ToTable("MafiaMembers");
                });

            modelBuilder.Entity("Domain.Entities.ShopAggregate.Ammunition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Ammunitions");
                });

            modelBuilder.Entity("Domain.Entities.ShopAggregate.Gun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("SupportAmmo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Guns");
                });

            modelBuilder.Entity("Domain.Entities.ShopAggregate.OrderShop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AmmunitonCount")
                        .HasColumnType("integer");

                    b.Property<string>("AmmunitonName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GunName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MafiaMemberId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MafiaMemberId");

                    b.ToTable("OrderShops");
                });

            modelBuilder.Entity("Domain.Entities.MainAggregate.FinancialReports", b =>
                {
                    b.HasOne("Domain.Entities.MainAggregate.MafiaCompany", null)
                        .WithMany("FinancialReports")
                        .HasForeignKey("MafiaCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.MainAggregate.MafiaCompany", b =>
                {
                    b.HasOne("Domain.Entities.MainAggregate.MafiaFamily", null)
                        .WithMany("MafiaCompanies")
                        .HasForeignKey("MafiaFamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.MainAggregate.MafiaMember", b =>
                {
                    b.HasOne("Domain.Entities.MainAggregate.MafiaFamily", null)
                        .WithMany("MafiaMembers")
                        .HasForeignKey("MafiaFamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.ShopAggregate.OrderShop", b =>
                {
                    b.HasOne("Domain.Entities.MainAggregate.MafiaMember", null)
                        .WithMany("OrderShops")
                        .HasForeignKey("MafiaMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.MainAggregate.MafiaCompany", b =>
                {
                    b.Navigation("FinancialReports");
                });

            modelBuilder.Entity("Domain.Entities.MainAggregate.MafiaFamily", b =>
                {
                    b.Navigation("MafiaCompanies");

                    b.Navigation("MafiaMembers");
                });

            modelBuilder.Entity("Domain.Entities.MainAggregate.MafiaMember", b =>
                {
                    b.Navigation("OrderShops");
                });
#pragma warning restore 612, 618
        }
    }
}
