// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(MafiaApiDbContext))]
    [Migration("20230707073207_MafiaFamily")]
    partial class MafiaFamily
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.FinancialReports", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("Expense")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FamilyDonate")
                        .HasColumnType("numeric");

                    b.Property<int>("MafiaCompanyId")
                        .HasColumnType("integer");

                    b.Property<decimal>("NetIncome")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("MafiaCompanyId");

                    b.ToTable("FinancialReports");
                });

            modelBuilder.Entity("Domain.Entities.MafiaCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("MafiaFamilyId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("MafiaFamilyId");

                    b.ToTable("MafiaCompanies");
                });

            modelBuilder.Entity("Domain.Entities.MafiaFamily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("MafiaFamilies");
                });

            modelBuilder.Entity("Domain.Entities.MafiaMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Birthday")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("MafiaFamilyId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("MafiaFamilyId");

                    b.ToTable("MafiaMembers");
                });

            modelBuilder.Entity("Domain.Entities.FinancialReports", b =>
                {
                    b.HasOne("Domain.Entities.MafiaCompany", null)
                        .WithMany("FinancialReports")
                        .HasForeignKey("MafiaCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.MafiaCompany", b =>
                {
                    b.HasOne("Domain.Entities.MafiaFamily", null)
                        .WithMany("MafiaCompanies")
                        .HasForeignKey("MafiaFamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.MafiaMember", b =>
                {
                    b.HasOne("Domain.Entities.MafiaFamily", null)
                        .WithMany("MafiaMembers")
                        .HasForeignKey("MafiaFamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.MafiaCompany", b =>
                {
                    b.Navigation("FinancialReports");
                });

            modelBuilder.Entity("Domain.Entities.MafiaFamily", b =>
                {
                    b.Navigation("MafiaCompanies");

                    b.Navigation("MafiaMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
